workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      java: "21"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
    scripts:
      - name: Run unit tests
        script: |
          ./gradlew app:testDebugUnitTest
      - name: Run Android Lint
        script: |
          ./gradlew app:lintDebug
      - name: Build Android App Bundle (AAB)
        script: |
          ./gradlew app:bundleDebug
      - name: Build Android App (APK)
        script: |
          ./gradlew app:assembleDebug
    artifacts:
      - app/build/outputs/bundle/debug/*.aab
      - app/build/outputs/apk/debug/*.apk