mutation Register($username: String!, $email: String!, $password: String!) {
    register(username: $username, email: $email, password: $password) {
        token
    }
}

mutation Login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
        token
    }
}

mutation UpdateProfile($displayName: String, $imageProfile: String) {
    updateProfile(displayName: $displayName, imageProfile: $imageProfile) {
        id
        username
        imageProfile
        displayName
    }
}
