name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - run: |
        javac --version

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew
    # - name: Build with Gradle
    #   run: ./gradlew build
